/**
 * Animation Presets
 * Pre-configured animation templates for common use cases
 */

const ANIMATION_PRESETS = {
    // Entrance animations
    fadeIn: {
        name: "Fade In",
        category: "entrance",
        type: "fadeIn",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInUp: {
        name: "Slide In Up",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "up",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInDown: {
        name: "Slide In Down",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "down",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInLeft: {
        name: "Slide In Left",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "left",
        startOpacity: 0,
        endOpacity: 1,
    },
    slideInRight: {
        name: "Slide In Right",
        category: "entrance",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        direction: "right",
        startOpacity: 0,
        endOpacity: 1,
    },
    zoomIn: {
        name: "Zoom In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startScale: 0.5,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    popIn: {
        name: "Pop In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 400,
        delay: 0,
        easing: "easeOut",
        startScale: 0.3,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    bounce: {
        name: "Bounce In",
        category: "entrance",
        type: "scaleInPlace",
        duration: 800,
        delay: 0,
        easing: "easeOutElastic",
        startScale: 0,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },

    // Exit animations
    fadeOut: {
        name: "Fade Out",
        category: "exit",
        type: "fadeOut",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutUp: {
        name: "Slide Out Up",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "up",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutDown: {
        name: "Slide Out Down",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "down",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutLeft: {
        name: "Slide Out Left",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "left",
        startOpacity: 1,
        endOpacity: 0,
    },
    slideOutRight: {
        name: "Slide Out Right",
        category: "exit",
        type: "transform",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        direction: "right",
        startOpacity: 1,
        endOpacity: 0,
    },
    zoomOut: {
        name: "Zoom Out",
        category: "exit",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeIn",
        startScale: 1,
        startOpacity: 1,
        endScale: 0,
        endOpacity: 0,
    },

    // Emphasis animations
    pulse: {
        name: "Pulse",
        category: "emphasis",
        type: "scaleInPlace",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        startScale: 1,
        endScale: 1.1,
    },
    rotate: {
        name: "Rotate",
        category: "emphasis",
        type: "rotate",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        rotation: 360,
    },
    spin: {
        name: "Spin",
        category: "emphasis",
        type: "rotate",
        duration: 1000,
        delay: 0,
        easing: "linear",
        rotation: 360,
    },

    // Scientific presets
    drawPath: {
        name: "Draw Path",
        category: "scientific",
        type: "write",
        duration: 1200,
        delay: 0,
        easing: "easeOut",
    },
    createObject: {
        name: "Create",
        category: "scientific",
        type: "create",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0,
        endOpacity: 1,
    },
    uncreateObject: {
        name: "Uncreate",
        category: "scientific",
        type: "uncreate",
        duration: 800,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0,
    },

    // Cinematic presets
    cinematicEnter: {
        name: "Cinematic Enter",
        category: "cinematic",
        type: "scaleInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeOutBack",
        startScale: 0.8,
        startOpacity: 0,
        endScale: 1,
        endOpacity: 1,
    },
    cinematicExit: {
        name: "Cinematic Exit",
        category: "cinematic",
        type: "scaleInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeInBack",
        startScale: 1,
        startOpacity: 1,
        endScale: 0.8,
        endOpacity: 0,
    },

    // Minimal presets
    subtleEnter: {
        name: "Subtle Enter",
        category: "minimal",
        type: "fadeIn",
        duration: 300,
        delay: 0,
        easing: "easeOut",
        startOpacity: 0.7,
        endOpacity: 1,
    },
    subtleExit: {
        name: "Subtle Exit",
        category: "minimal",
        type: "fadeOut",
        duration: 300,
        delay: 0,
        easing: "easeIn",
        startOpacity: 1,
        endOpacity: 0.7,
    },
    // NEW: Color animations
    colorFadeFromRed: {
        name: "Color Fade (Red → Neutral)",
        category: "color",
        type: "colorShift",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        startColor: "#ff4444",
        endColor: "#000000",
        colorProperty: "fill",
    },
    colorPulse: {
        name: "Color Pulse",
        category: "color",
        type: "colorShift",
        duration: 600,
        delay: 0,
        easing: "easeInOut",
        startColor: "#4488ff",
        endColor: "#44ffff",
        colorProperty: "fill",
    },
    highlightBlink: {
        name: "Highlight Blink",
        category: "color",
        type: "colorShift",
        duration: 400,
        delay: 0,
        easing: "easeOut",
        startColor: "#ffff00",
        endColor: "#000000",
        colorProperty: "fill",
    },
    // NEW: Position animations
    moveRight: {
        name: "Move Right",
        category: "position",
        type: "moveInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 100,
        startY: 0,
        endY: 0,
    },
    moveUp: {
        name: "Move Up",
        category: "position",
        type: "moveInPlace",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 0,
        startY: 0,
        endY: -100,
    },
    floatAround: {
        name: "Float Around",
        category: "position",
        type: "moveInPlace",
        duration: 1200,
        delay: 0,
        easing: "easeInOut",
        startX: 0,
        endX: 50,
        startY: 0,
        endY: -30,
    },
    // NEW: Scale animations
    scaleUpDown: {
        name: "Scale Up & Down",
        category: "scale",
        type: "scaleXY",
        duration: 800,
        delay: 0,
        easing: "easeInOut",
        startScaleX: 1,
        endScaleX: 1.2,
        startScaleY: 1,
        endScaleY: 0.9,
    },
    stretchHorizontal: {
        name: "Stretch Horizontal",
        category: "scale",
        type: "scaleXY",
        duration: 600,
        delay: 0,
        easing: "easeOut",
        startScaleX: 0.5,
        endScaleX: 1,
        startScaleY: 1,
        endScaleY: 1,
    },
    // NEW: SVG stroke animations
    strokeDraw: {
        name: "Stroke Draw",
        category: "svg",
        type: "strokeAnimate",
        duration: 1000,
        delay: 0,
        easing: "easeOut",
        startStrokeWidth: 0,
        endStrokeWidth: 2,
    },
    strokeThicken: {
        name: "Stroke Thicken",
        category: "svg",
        type: "strokeAnimate",
        duration: 500,
        delay: 0,
        easing: "easeInOut",
        startStrokeWidth: 1,
        endStrokeWidth: 4,
    },
    // NEW: Combined transforms
    slideAndGrow: {
        name: "Slide & Grow",
        category: "advanced",
        type: "combinedTransform",
        duration: 800,
        delay: 0,
        easing: "easeOut",
        startX: -100,
        endX: 0,
        startY: 0,
        endY: 0,
        startScaleX: 0.5,
        endScaleX: 1,
        startScaleY: 0.5,
        endScaleY: 1,
        startRotation: -10,
        endRotation: 0,
    },
    spinAndMove: {
        name: "Spin & Move",
        category: "advanced",
        type: "combinedTransform",
        duration: 1000,
        delay: 0,
        easing: "easeOut",
        startX: 0,
        endX: 150,
        startY: 0,
        endY: -50,
        startScaleX: 1,
        endScaleX: 1,
        startScaleY: 1,
        endScaleY: 1,
        startRotation: 0,
        endRotation: 360,
    },
};

const PRESET_CATEGORIES = {
    entrance: {
        name: "Entrance",
        icon: "arrow-right",
        description: "Animations for objects appearing",
    },
    exit: {
        name: "Exit",
        icon: "arrow-left",
        description: "Animations for objects disappearing",
    },
    emphasis: {
        name: "Emphasis",
        icon: "star",
        description: "Animations for emphasis",
    },
    scientific: {
        name: "Scientific",
        icon: "microscope",
        description: "Animations for scientific visualization",
    },
    cinematic: {
        name: "Cinematic",
        icon: "film",
        description: "Cinematic motion effects",
    },
    minimal: {
        name: "Minimal",
        icon: "minimize-2",
        description: "Subtle, refined animations",
    },
};

function getPreset(presetName) {
    return ANIMATION_PRESETS[presetName] || null;
}

function getPresetsByCategory(category) {
    return Object.entries(ANIMATION_PRESETS)
        .filter(([_, preset]) => preset.category === category)
        .map(([name, preset]) => ({ name, ...preset }));
}

function getAllPresets() {
    return Object.entries(ANIMATION_PRESETS).map(([name, preset]) => ({ name, ...preset }));
}

function createPresetAnimation(presetName, overrides = {}) {
    const preset = getPreset(presetName);
    if (!preset) return null;

    return {
        ...preset,
        ...overrides,
        id: generateId("anim"),
    };
}

// Export presets
if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        ANIMATION_PRESETS,
        PRESET_CATEGORIES,
        getPreset,
        getPresetsByCategory,
        getAllPresets,
        createPresetAnimation,
    };
}
